language: csharp

solution: Grpc.Tools.MsBuild.sln

sudo: required

matrix:
  include:
    - os: linux
      mono: none
    - os: osx
      osx_image: xcode9
      mono: none
    - os: linux
      mono: latest
      env: MONO_BUILD=1
    - os: osx
      osx_image: xcode9
      mono: latest
      env: MONO_BUILD=1

git:
  depth: 3
  submodules: false

install:
  - git fetch --unshallow
  - git submodule update --init

script:
  - chmod +x ./build.sh
  - ./build.sh
