language: csharp

solution: Grpc.Tools.MsBuild.sln

sudo: required

matrix:
  include:
    - os: linux
      mono: none
    - os: osx
      mono: none
    - os: linux
      mono: latest
      env: MONO_BUILD
    - os: osx
      mono: latest
      env: MONO_BUILD

git:
  depth: 3
  submodules: false

install:
  - git fetch --unshallow
  - git submodule update --init

script:
  - chmod +x ./build.sh
  - ./build.sh
