image: Visual Studio 2017

configuration: Release

deploy:
  provider: Environment
  name: myget

install:
  - git submodule update --init

before_build:
  - dotnet restore

build:
  parallel: true
  project: Grpc.Tools.MsBuild.sln

test: off

artifacts:
  - path: '**\*.nupkg'
    name: NuGet Package
